#!/usr/bin/env npx tsx
/**
 * Deploy SynapseAgentRegistry to Base Sepolia
 *
 * Usage:
 *   npx tsx scripts/deploy-registry.ts
 *
 * Environment:
 *   DEPLOYER_PRIVATE_KEY - Private key for deployment (required)
 *   BASE_SEPOLIA_RPC_URL - RPC URL (default: https://sepolia.base.org)
 */

import { ethers } from 'ethers';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Contract ABI and bytecode (compiled from SynapseAgentRegistry.sol)
// In production, this would be generated by Hardhat/Foundry
const CONTRACT_ABI = [
  // Constructor
  "constructor()",
  // Events
  "event AgentRegistered(bytes32 indexed agentId, string name, address indexed walletAddress, string agentJsonUrl, uint256 timestamp)",
  "event AgentUpdated(bytes32 indexed agentId, string name, string agentJsonUrl, uint256 timestamp)",
  "event AgentDeactivated(bytes32 indexed agentId, uint256 timestamp)",
  "event ReputationUpdated(bytes32 indexed agentId, uint256 oldScore, uint256 newScore, uint256 totalFeedback, uint256 timestamp)",
  "event FeedbackSubmitted(bytes32 indexed agentId, address indexed submitter, uint8 rating, bool success, uint256 timestamp)",
  // Read functions
  "function owner() view returns (address)",
  "function agents(bytes32) view returns (string name, string agentJsonUrl, address walletAddress, uint256 reputation, uint256 totalFeedback, uint256 positiveFeedback, uint256 registeredAt, uint256 lastUpdated, bool isActive)",
  "function walletToAgent(address) view returns (bytes32)",
  "function agentIds(uint256) view returns (bytes32)",
  "function getAgent(bytes32 agentId) view returns (tuple(string name, string agentJsonUrl, address walletAddress, uint256 reputation, uint256 totalFeedback, uint256 positiveFeedback, uint256 registeredAt, uint256 lastUpdated, bool isActive))",
  "function getAgentByWallet(address wallet) view returns (tuple(string name, string agentJsonUrl, address walletAddress, uint256 reputation, uint256 totalFeedback, uint256 positiveFeedback, uint256 registeredAt, uint256 lastUpdated, bool isActive))",
  "function getAgentId(address wallet) view returns (bytes32)",
  "function getTotalAgents() view returns (uint256)",
  "function getReputation(bytes32 agentId) view returns (uint256)",
  "function isAgentActive(bytes32 agentId) view returns (bool)",
  // Write functions
  "function registerAgent(string name, string agentJsonUrl, address walletAddress) returns (bytes32 agentId)",
  "function updateAgent(bytes32 agentId, string name, string agentJsonUrl)",
  "function deactivateAgent(bytes32 agentId)",
  "function submitFeedback(bytes32 agentId, uint8 rating, bool success)",
  "function setReputation(bytes32 agentId, uint256 newReputation)",
  "function transferOwnership(address newOwner)"
];

// Minimal bytecode for a mock deployment (actual deployment would use compiled bytecode)
// This allows testing the deployment flow
const MOCK_BYTECODE = "0x608060405234801561001057600080fd5b50336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555061001961001e565b61002f565b600180600082825461003091906100c7565b92505081905550565b61010b806100486000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80638da5cb5b14603757806395d89b4114606c575b600080fd5b60005473ffffffffffffffffffffffffffffffffffffffff16604051908152602001604051809103910160405180910390f35b60405180604001604052806008815260200167556e6465706c6f7960c01b815250604051908190039060200160405180910390f35b634e487b7160e01b600052601160045260246000fdfea264697066735822122000000000000000000000000000000000000000000000000000000000000000006473";

async function main() {
  console.log('╔════════════════════════════════════════════════════════════════════╗');
  console.log('║           SYNAPSE AGENT REGISTRY DEPLOYMENT                        ║');
  console.log('╚════════════════════════════════════════════════════════════════════╝');
  console.log();

  // Configuration
  const rpcUrl = process.env.BASE_SEPOLIA_RPC_URL || 'https://sepolia.base.org';
  const privateKey = process.env.DEPLOYER_PRIVATE_KEY || process.env.EIGENCLOUD_PRIVATE_KEY;

  if (!privateKey) {
    console.error('❌ Error: DEPLOYER_PRIVATE_KEY or EIGENCLOUD_PRIVATE_KEY not set');
    console.error('   Set the environment variable with a funded wallet private key');
    process.exit(1);
  }

  // Connect to network
  console.log(`📡 Connecting to Base Sepolia...`);
  console.log(`   RPC: ${rpcUrl}`);

  const provider = new ethers.JsonRpcProvider(rpcUrl);
  const wallet = new ethers.Wallet(privateKey, provider);

  console.log(`   Deployer: ${wallet.address}`);

  // Check balance
  const balance = await provider.getBalance(wallet.address);
  const balanceEth = ethers.formatEther(balance);
  console.log(`   Balance: ${balanceEth} ETH`);

  if (balance === 0n) {
    console.error('❌ Error: Deployer wallet has no ETH for gas');
    console.error('   Fund the wallet at: https://www.alchemy.com/faucets/base-sepolia');
    process.exit(1);
  }

  // Note: For actual deployment, you would:
  // 1. Compile the contract with solc, Hardhat, or Foundry
  // 2. Get the actual bytecode
  // 3. Deploy with that bytecode
  //
  // For now, we'll show the expected deployment flow

  console.log();
  console.log('📝 Contract: SynapseAgentRegistry');
  console.log('   File: contracts/SynapseAgentRegistry.sol');
  console.log();

  // Check if we should do a real deployment
  const doRealDeploy = process.env.DEPLOY_REAL === 'true';

  if (doRealDeploy) {
    console.log('⚠️  Real deployment requires compiled bytecode');
    console.log('   Install Hardhat or Foundry and compile the contract first:');
    console.log();
    console.log('   # Using Hardhat:');
    console.log('   npm install --save-dev hardhat @nomicfoundation/hardhat-toolbox');
    console.log('   npx hardhat compile');
    console.log();
    console.log('   # Using Foundry:');
    console.log('   curl -L https://foundry.paradigm.xyz | bash');
    console.log('   foundryup');
    console.log('   forge build');
    console.log();
  } else {
    console.log('🔬 Simulation mode (set DEPLOY_REAL=true for actual deployment)');
    console.log();

    // Simulate deployment info
    const mockContractAddress = ethers.getCreateAddress({
      from: wallet.address,
      nonce: await provider.getTransactionCount(wallet.address)
    });

    console.log('📋 Deployment Preview:');
    console.log(`   Expected Contract Address: ${mockContractAddress}`);
    console.log(`   Estimated Gas: ~1,500,000`);
    console.log(`   Estimated Cost: ~0.0015 ETH`);
    console.log();

    // Create deployment info file
    const deployInfo = {
      network: 'base-sepolia',
      chainId: 84532,
      deployer: wallet.address,
      expectedAddress: mockContractAddress,
      rpcUrl,
      contractName: 'SynapseAgentRegistry',
      contractFile: 'contracts/SynapseAgentRegistry.sol',
      abi: CONTRACT_ABI,
      timestamp: new Date().toISOString(),
      status: 'pending',
      note: 'Contract not yet deployed - compile with Hardhat/Foundry first'
    };

    const outputPath = path.join(__dirname, '..', 'deployment-info.json');
    fs.writeFileSync(outputPath, JSON.stringify(deployInfo, null, 2));
    console.log(`💾 Deployment info saved to: deployment-info.json`);
  }

  console.log();
  console.log('📖 Next Steps:');
  console.log('   1. Install Hardhat: npm install --save-dev hardhat');
  console.log('   2. Initialize: npx hardhat init');
  console.log('   3. Compile: npx hardhat compile');
  console.log('   4. Deploy: DEPLOY_REAL=true npx tsx scripts/deploy-registry.ts');
  console.log();
  console.log('🔗 After deployment, set environment variable:');
  console.log('   ERC8004_REGISTRY_ADDRESS=<deployed-contract-address>');
  console.log();
}

main().catch(console.error);
